Added description modal
synogram/client pull request #17
Opened 2020-12-08 02:51 UTC by EwhanHan

2020-12-08 06:02 UTC, jhwan7 commented on src/containers/Descriptions/Descriptions.js
> +  };
try to remove unused code

2020-12-08 06:05 UTC, jhwan7 commented on src/containers/Descriptions/Descriptions.js
> +    console.log(this.myRef);
remove console.logs

2020-12-08 06:05 UTC, jhwan7 commented
![image](https://user-images.githubusercontent.com/46652246/101446513-779d3f80-38f1-11eb-991f-8dd18f52b80d.png)

the button doesnt seem to expand fully across the top

2020-12-08 06:14 UTC, jhwan7 commented
![image](https://user-images.githubusercontent.com/46652246/101447107-8df7cb00-38f2-11eb-9e4d-fb183d58922e.png)
I don't think this quiet matches with the design, only the top of the modal should be displayed on initial page. Also button icon is wrong "+" should be changed to "^"

2020-12-08 06:15 UTC, jhwan7 requested changes
try to reflect my comments

2020-12-09 01:51 UTC, EwhanHan commented on src/containers/Descriptions/Descriptions.js
> +    console.log(this.myRef);
gotcha

2020-12-09 01:54 UTC, EwhanHan commented
will be adding pushed footer and change icons shortly

2021-01-19 05:17 UTC, jhwan7 approved these changes

2021-01-19 05:20 UTC, merged